### ISSUE TITLE
Uncaught TypeError: get_general is not a function  at HTMLDocument.<anonymous> (settings.tabs.js:64:2)    

### ISSUE THREAD

**Issue by christosal** [globaldyne/parfumvault#186]
**Describe the bug**
Not loading the settings tab at all

**To Reproduce**
1. Installed v11.3 and mariadb 10.5

Here is the docker-compose.yml 
```
version: '3.8'
services:
  pvdb:
    image: mariadb:10.5
    command: '--default-authentication-plugin=mysql_native_password --innodb-flush-method=fsync'
    volumes:
      - db_data:/var/lib/mysql
      - /home/user/perfumersvault/html/db:/html/db
    environment:
      MYSQL_ROOT_PASSWORD: pvault
      MYSQL_DATABASE: pvault
      MYSQL_USER: pvault
      MYSQL_PASSWORD: pvault
    expose:
      - 3306
    restart: always

  pvault:
    image: globaldyne/perfumersvault:v11.3
    ports:
      - "8000:8000"
    environment:
      PLATFORM: CLOUD
      DB_HOST: pvdb
      DB_USER: pvault
      DB_PASS: pvault
      DB_NAME: pvault
#    volumes:
 #     - /home/user/perfumersvault/html:/html  # Mount the entire HTML folder
    restart: always

volumes:
  db_data:
```

**Screenshots**
![image](https://github.com/user-attachments/assets/a9c77d7f-be68-418b-a641-9ead7cbcd284)
